"""empty message

Revision ID: 4f8e1521c8e1
Revises: None
Create Date: 2016-09-16 16:49:31.676846

"""

# revision identifiers, used by Alembic.
revision = '4f8e1521c8e1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('current_mileage', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'current_mileage')
    ### end Alembic commands ###
