"""empty message

Revision ID: 5047dfeaed2d
Revises: None
Create Date: 2016-09-16 16:56:29.611876

"""

# revision identifiers, used by Alembic.
revision = '5047dfeaed2d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_mileage', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('current_mileage')

    ### end Alembic commands ###
