"""empty message

Revision ID: 54064edf1d86
Revises: None
Create Date: 2016-09-16 19:24:22.941194

"""

# revision identifiers, used by Alembic.
revision = '54064edf1d86'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('news_subscriptions', postgresql.JSON(), nullable=True))
    op.drop_column('user', 'data')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'news_subscriptions')
    ### end Alembic commands ###
