"""empty message

Revision ID: 7cbbed8e7bbc
Revises: 4f8e1521c8e1
Create Date: 2016-09-16 16:49:54.391316

"""

# revision identifiers, used by Alembic.
revision = '7cbbed8e7bbc'
down_revision = '4f8e1521c8e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'current_mileage')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('current_mileage', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
