"""empty message

Revision ID: f285b3be370d
Revises: 39480896bd81
Create Date: 2016-09-16 16:56:55.260668

"""

# revision identifiers, used by Alembic.
revision = 'f285b3be370d'
down_revision = '39480896bd81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_mileage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transmission_type', sa.Enum('automatic', 'manual', name='transmission_types'), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('transmission_type')
        batch_op.drop_column('current_mileage')

    ### end Alembic commands ###
